"""Build and execute the Fashion MNIST CNN assignment notebook."""

from __future__ import annotations

import json
from pathlib import Path

NOTEBOOK_PATH = Path(__file__).with_name("Fashion_MNIST_CNN.ipynb")

CELLS = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Fashion MNIST CNN — Model Development & Tuning\n",
            "\n",
            "This notebook builds and evaluates convolutional neural networks for Fashion MNIST\n",
            "image classification. We start with an in-class baseline CNN, run controlled\n",
            "one-factor-at-a-time experiments, then use Optuna to search for a stronger final model.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. Setup and data loading"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import warnings\n",
            "warnings.filterwarnings(\"ignore\")\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "import tensorflow as tf\n",
            "from tensorflow import keras\n",
            "from tensorflow.keras import layers, regularizers\n",
            "\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.metrics import classification_report, confusion_matrix\n",
            "\n",
            "import optuna\n",
            "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
            "\n",
            "RANDOM_STATE = 42\n",
            "EPOCHS = 12\n",
            "PATIENCE = 4\n",
            "BATCH_SIZE = 128\n",
            "NUM_CLASSES = 10\n",
            "\n",
            "CLASS_NAMES = [\n",
            "    \"T-shirt/top\", \"Trouser\", \"Pullover\", \"Dress\", \"Coat\",\n",
            "    \"Sandal\", \"Shirt\", \"Sneaker\", \"Bag\", \"Ankle boot\",\n",
            "]\n",
            "\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "np.random.seed(RANDOM_STATE)\n",
            "sns.set_theme(style=\"whitegrid\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "(X_train_full, y_train_full), (X_test, y_test) = keras.datasets.fashion_mnist.load_data()\n",
            "\n",
            "print(\"Training shape:\", X_train_full.shape)\n",
            "print(\"Test shape:\", X_test.shape)\n",
            "print(\"Label range:\", y_train_full.min(), \"to\", y_train_full.max())\n",
            "\n",
            "pd.Series(y_train_full).value_counts().sort_index().rename(\"count\").to_frame()\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "fig, axes = plt.subplots(2, 5, figsize=(12, 5))\n",
            "for ax, idx in zip(axes.ravel(), range(10)):\n",
            "    ax.imshow(X_train_full[idx], cmap=\"gray\")\n",
            "    ax.set_title(CLASS_NAMES[y_train_full[idx]], fontsize=10)\n",
            "    ax.axis(\"off\")\n",
            "plt.suptitle(\"Sample Fashion MNIST images\", y=1.02)\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Preprocessing\n",
            "\n",
            "Pixels are scaled to `[0, 1]`, a channel dimension is added for Keras CNNs, and a\n",
            "validation split is carved out of the official training set. The official test set\n",
            "remains untouched until the final evaluation.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "X_train_full = X_train_full.astype(\"float32\") / 255.0\n",
            "X_test = X_test.astype(\"float32\") / 255.0\n",
            "\n",
            "X_train_full = X_train_full[..., np.newaxis]\n",
            "X_test = X_test[..., np.newaxis]\n",
            "\n",
            "X_train, X_val, y_train, y_val = train_test_split(\n",
            "    X_train_full,\n",
            "    y_train_full,\n",
            "    test_size=0.1,\n",
            "    random_state=RANDOM_STATE,\n",
            "    stratify=y_train_full,\n",
            ")\n",
            "\n",
            "print(\"Train:\", X_train.shape, \"| Val:\", X_val.shape, \"| Test:\", X_test.shape)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 3. Reusable training utilities"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def plot_history(history, title=\"Training history\"):\n",
            "    hist = history.history\n",
            "    epochs = range(1, len(hist[\"loss\"]) + 1)\n",
            "\n",
            "    fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
            "\n",
            "    axes[0].plot(epochs, hist[\"loss\"], label=\"train\")\n",
            "    axes[0].plot(epochs, hist[\"val_loss\"], label=\"val\")\n",
            "    axes[0].set_title(\"Loss\")\n",
            "    axes[0].set_xlabel(\"Epoch\")\n",
            "    axes[0].legend()\n",
            "\n",
            "    axes[1].plot(epochs, hist[\"accuracy\"], label=\"train\")\n",
            "    axes[1].plot(epochs, hist[\"val_accuracy\"], label=\"val\")\n",
            "    axes[1].set_title(\"Accuracy\")\n",
            "    axes[1].set_xlabel(\"Epoch\")\n",
            "    axes[1].legend()\n",
            "\n",
            "    fig.suptitle(title)\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "\n",
            "def train_model(model, X_tr, y_tr, X_va, y_va, epochs=EPOCHS, batch_size=BATCH_SIZE,\n",
            "                patience=PATIENCE, augment=False, verbose=0):\n",
            "    callbacks = [\n",
            "        keras.callbacks.EarlyStopping(\n",
            "            monitor=\"val_loss\", patience=patience, restore_best_weights=True\n",
            "        )\n",
            "    ]\n",
            "\n",
            "    if augment:\n",
            "        datagen = keras.Sequential([\n",
            "            layers.RandomFlip(\"horizontal\"),\n",
            "            layers.RandomRotation(0.08),\n",
            "            layers.RandomZoom(0.08),\n",
            "        ])\n",
            "        train_ds = (\n",
            "            tf.data.Dataset.from_tensor_slices((X_tr, y_tr))\n",
            "            .shuffle(len(X_tr), seed=RANDOM_STATE)\n",
            "            .batch(batch_size)\n",
            "            .map(lambda x, y: (datagen(x, training=True), y), num_parallel_calls=tf.data.AUTOTUNE)\n",
            "            .prefetch(tf.data.AUTOTUNE)\n",
            "        )\n",
            "        val_ds = tf.data.Dataset.from_tensor_slices((X_va, y_va)).batch(batch_size)\n",
            "        return model.fit(train_ds, validation_data=val_ds, epochs=epochs,\n",
            "                         callbacks=callbacks, verbose=verbose)\n",
            "\n",
            "    return model.fit(\n",
            "        X_tr, y_tr,\n",
            "        validation_data=(X_va, y_va),\n",
            "        epochs=epochs,\n",
            "        batch_size=batch_size,\n",
            "        callbacks=callbacks,\n",
            "        verbose=verbose,\n",
            "    )\n",
            "\n",
            "\n",
            "def evaluate_model(model, X, y, split_name=\"Test\"):\n",
            "    loss, acc = model.evaluate(X, y, verbose=0)\n",
            "    y_pred = np.argmax(model.predict(X, verbose=0), axis=1)\n",
            "    return {\n",
            "        \"split\": split_name,\n",
            "        \"loss\": loss,\n",
            "        \"accuracy\": acc,\n",
            "        \"y_pred\": y_pred,\n",
            "    }\n",
            "\n",
            "\n",
            "def build_baseline_cnn(learning_rate=1e-3):\n",
            "    model = keras.Sequential([\n",
            "        layers.Input(shape=(28, 28, 1)),\n",
            "        layers.Conv2D(32, (3, 3), activation=\"relu\"),\n",
            "        layers.MaxPooling2D((2, 2)),\n",
            "        layers.Flatten(),\n",
            "        layers.Dense(64, activation=\"relu\"),\n",
            "        layers.Dense(NUM_CLASSES, activation=\"softmax\"),\n",
            "    ])\n",
            "    model.compile(\n",
            "        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),\n",
            "        loss=\"sparse_categorical_crossentropy\",\n",
            "        metrics=[\"accuracy\"],\n",
            "    )\n",
            "    return model\n",
            "\n",
            "\n",
            "def build_deep_cnn(dropout=0.0, l2=0.0, learning_rate=1e-3, dense_units=128):\n",
            "    reg = regularizers.l2(l2) if l2 > 0 else None\n",
            "    model_layers = [\n",
            "        layers.Input(shape=(28, 28, 1)),\n",
            "        layers.Conv2D(32, (3, 3), activation=\"relu\", padding=\"same\",\n",
            "                      kernel_regularizer=reg),\n",
            "        layers.MaxPooling2D((2, 2)),\n",
            "        layers.Conv2D(64, (3, 3), activation=\"relu\", padding=\"same\",\n",
            "                      kernel_regularizer=reg),\n",
            "        layers.MaxPooling2D((2, 2)),\n",
            "        layers.Flatten(),\n",
            "        layers.Dense(dense_units, activation=\"relu\", kernel_regularizer=reg),\n",
            "    ]\n",
            "    if dropout > 0:\n",
            "        model_layers.append(layers.Dropout(dropout))\n",
            "    model_layers.append(layers.Dense(NUM_CLASSES, activation=\"softmax\"))\n",
            "    model = keras.Sequential(model_layers)\n",
            "    model.compile(\n",
            "        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),\n",
            "        loss=\"sparse_categorical_crossentropy\",\n",
            "        metrics=[\"accuracy\"],\n",
            "    )\n",
            "    return model\n",
            "\n",
            "\n",
            "def build_tuned_cnn(filters_1, filters_2, dense_units, dropout, l2, learning_rate):\n",
            "    reg = regularizers.l2(l2) if l2 > 0 else None\n",
            "    model = keras.Sequential([\n",
            "        layers.Input(shape=(28, 28, 1)),\n",
            "        layers.Conv2D(filters_1, (3, 3), activation=\"relu\", padding=\"same\",\n",
            "                      kernel_regularizer=reg),\n",
            "        layers.MaxPooling2D((2, 2)),\n",
            "        layers.Conv2D(filters_2, (3, 3), activation=\"relu\", padding=\"same\",\n",
            "                      kernel_regularizer=reg),\n",
            "        layers.MaxPooling2D((2, 2)),\n",
            "        layers.Flatten(),\n",
            "        layers.Dense(dense_units, activation=\"relu\", kernel_regularizer=reg),\n",
            "        layers.Dropout(dropout),\n",
            "        layers.Dense(NUM_CLASSES, activation=\"softmax\"),\n",
            "    ])\n",
            "    model.compile(\n",
            "        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),\n",
            "        loss=\"sparse_categorical_crossentropy\",\n",
            "        metrics=[\"accuracy\"],\n",
            "    )\n",
            "    return model\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Baseline CNN\n",
            "\n",
            "The baseline mirrors the in-class MNIST CNN: one convolution block, flatten, and two dense layers.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "tf.keras.backend.clear_session()\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "baseline_model = build_baseline_cnn()\n",
            "baseline_model.summary()\n",
            "\n",
            "baseline_history = train_model(\n",
            "    baseline_model, X_train, y_train, X_val, y_val, verbose=1\n",
            ")\n",
            "plot_history(baseline_history, \"Baseline CNN\")\n",
            "\n",
            "baseline_val = evaluate_model(baseline_model, X_val, y_val, \"Validation\")\n",
            "print(f\"Baseline validation accuracy: {baseline_val['accuracy']:.4f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. One-factor-at-a-time experiments\n",
            "\n",
            "Each experiment changes **one** design choice relative to the previous best direction,\n",
            "while keeping preprocessing, epochs, and early stopping fixed.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Experiment A — Add a second convolution block (capacity)\n",
            "\n",
            "Hypothesis: a deeper feature extractor should improve validation accuracy on Fashion MNIST,\n",
            "which is harder than digit MNIST.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "tf.keras.backend.clear_session()\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "exp_a_model = build_deep_cnn(dropout=0.0, l2=0.0)\n",
            "exp_a_history = train_model(exp_a_model, X_train, y_train, X_val, y_val, verbose=1)\n",
            "plot_history(exp_a_history, \"Experiment A: deeper CNN\")\n",
            "\n",
            "exp_a_val = evaluate_model(exp_a_model, X_val, y_val, \"Validation\")\n",
            "print(f\"Experiment A validation accuracy: {exp_a_val['accuracy']:.4f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Experiment B — Add dropout regularization (same architecture as A)\n",
            "\n",
            "Hypothesis: dropout should reduce the train/validation gap if Experiment A overfits.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "tf.keras.backend.clear_session()\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "exp_b_model = build_deep_cnn(dropout=0.3, l2=0.0)\n",
            "exp_b_history = train_model(exp_b_model, X_train, y_train, X_val, y_val, verbose=1)\n",
            "plot_history(exp_b_history, \"Experiment B: deeper CNN + dropout\")\n",
            "\n",
            "exp_b_val = evaluate_model(exp_b_model, X_val, y_val, \"Validation\")\n",
            "print(f\"Experiment B validation accuracy: {exp_b_val['accuracy']:.4f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Experiment C — Add data augmentation (same architecture + dropout as B)\n",
            "\n",
            "Hypothesis: mild augmentation improves generalization without changing model capacity.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "tf.keras.backend.clear_session()\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "exp_c_model = build_deep_cnn(dropout=0.3, l2=0.0)\n",
            "exp_c_history = train_model(\n",
            "    exp_c_model, X_train, y_train, X_val, y_val, augment=True, verbose=1\n",
            ")\n",
            "plot_history(exp_c_history, \"Experiment C: deeper CNN + dropout + augmentation\")\n",
            "\n",
            "exp_c_val = evaluate_model(exp_c_model, X_val, y_val, \"Validation\")\n",
            "print(f\"Experiment C validation accuracy: {exp_c_val['accuracy']:.4f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Experiment D — Lower learning rate (same setup as C)\n",
            "\n",
            "Hypothesis: a smaller learning rate may find a better minimum when training with augmentation.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "tf.keras.backend.clear_session()\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "exp_d_model = build_deep_cnn(dropout=0.3, l2=0.0, learning_rate=5e-4)\n",
            "exp_d_history = train_model(\n",
            "    exp_d_model, X_train, y_train, X_val, y_val, augment=True, verbose=1\n",
            ")\n",
            "plot_history(exp_d_history, \"Experiment D: lower learning rate\")\n",
            "\n",
            "exp_d_val = evaluate_model(exp_d_model, X_val, y_val, \"Validation\")\n",
            "print(f\"Experiment D validation accuracy: {exp_d_val['accuracy']:.4f}\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "experiment_rows = []\n",
            "for name, history, val_metrics in [\n",
            "    (\"Baseline\", baseline_history, baseline_val),\n",
            "    (\"A: deeper\", exp_a_history, exp_a_val),\n",
            "    (\"B: +dropout\", exp_b_history, exp_b_val),\n",
            "    (\"C: +augment\", exp_c_history, exp_c_val),\n",
            "    (\"D: +lower LR\", exp_d_history, exp_d_val),\n",
            "]:\n",
            "    train_acc = history.history[\"accuracy\"][-1]\n",
            "    val_acc = history.history[\"val_accuracy\"][-1]\n",
            "    experiment_rows.append({\n",
            "        \"model\": name,\n",
            "        \"final_train_acc\": train_acc,\n",
            "        \"final_val_acc\": val_acc,\n",
            "        \"val_gap\": train_acc - val_acc,\n",
            "        \"best_val_acc\": max(history.history[\"val_accuracy\"]),\n",
            "        \"eval_val_acc\": val_metrics[\"accuracy\"],\n",
            "    })\n",
            "\n",
            "experiment_df = pd.DataFrame(experiment_rows)\n",
            "experiment_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Optuna hyperparameter search\n",
            "\n",
            "After the manual experiments, Optuna searches jointly over filter counts, dense width,\n",
            "dropout, L2 regularization, learning rate, and batch size. Each trial uses the same\n",
            "augmentation pipeline as Experiment C/D.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def optuna_objective(trial):\n",
            "    filters_1 = trial.suggest_categorical(\"filters_1\", [32, 48, 64])\n",
            "    filters_2 = trial.suggest_categorical(\"filters_2\", [64, 96, 128])\n",
            "    dense_units = trial.suggest_categorical(\"dense_units\", [64, 128, 256])\n",
            "    dropout = trial.suggest_float(\"dropout\", 0.1, 0.5)\n",
            "    l2 = trial.suggest_float(\"l2\", 1e-6, 1e-3, log=True)\n",
            "    learning_rate = trial.suggest_float(\"learning_rate\", 1e-4, 3e-3, log=True)\n",
            "    batch_size = trial.suggest_categorical(\"batch_size\", [64, 128, 256])\n",
            "\n",
            "    tf.keras.backend.clear_session()\n",
            "    tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "    model = build_tuned_cnn(\n",
            "        filters_1=filters_1,\n",
            "        filters_2=filters_2,\n",
            "        dense_units=dense_units,\n",
            "        dropout=dropout,\n",
            "        l2=l2,\n",
            "        learning_rate=learning_rate,\n",
            "    )\n",
            "\n",
            "    history = train_model(\n",
            "        model,\n",
            "        X_train,\n",
            "        y_train,\n",
            "        X_val,\n",
            "        y_val,\n",
            "        epochs=10,\n",
            "        batch_size=batch_size,\n",
            "        patience=3,\n",
            "        augment=True,\n",
            "        verbose=0,\n",
            "    )\n",
            "    return max(history.history[\"val_accuracy\"])\n",
            "\n",
            "\n",
            "study = optuna.create_study(\n",
            "    direction=\"maximize\",\n",
            "    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),\n",
            ")\n",
            "study.optimize(optuna_objective, n_trials=15, show_progress_bar=True)\n",
            "\n",
            "print(\"Best validation accuracy:\", round(study.best_value, 4))\n",
            "print(\"Best hyperparameters:\")\n",
            "for key, value in study.best_params.items():\n",
            "    print(f\"  {key}: {value}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Final model training and held-out test evaluation\n",
            "\n",
            "The final model uses Optuna's best settings, retrains on the combined train+validation split,\n",
            "and is evaluated once on the official test set.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "best = study.best_params\n",
            "\n",
            "tf.keras.backend.clear_session()\n",
            "tf.keras.utils.set_random_seed(RANDOM_STATE)\n",
            "\n",
            "final_model = build_tuned_cnn(\n",
            "    filters_1=best[\"filters_1\"],\n",
            "    filters_2=best[\"filters_2\"],\n",
            "    dense_units=best[\"dense_units\"],\n",
            "    dropout=best[\"dropout\"],\n",
            "    l2=best[\"l2\"],\n",
            "    learning_rate=best[\"learning_rate\"],\n",
            ")\n",
            "final_model.summary()\n",
            "\n",
            "X_final_train = np.concatenate([X_train, X_val], axis=0)\n",
            "y_final_train = np.concatenate([y_train, y_val], axis=0)\n",
            "\n",
            "final_history = train_model(\n",
            "    final_model,\n",
            "    X_final_train,\n",
            "    y_final_train,\n",
            "    X_val,\n",
            "    y_val,\n",
            "    epochs=EPOCHS,\n",
            "    batch_size=best[\"batch_size\"],\n",
            "    augment=True,\n",
            "    verbose=1,\n",
            ")\n",
            "plot_history(final_history, \"Final tuned CNN\")\n",
            "\n",
            "final_test = evaluate_model(final_model, X_test, y_test, \"Test\")\n",
            "print(f\"Final test accuracy: {final_test['accuracy']:.4f}\")\n",
            "print(f\"Final test loss: {final_test['loss']:.4f}\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "print(classification_report(y_test, final_test[\"y_pred\"], target_names=CLASS_NAMES))\n",
            "\n",
            "cm = confusion_matrix(y_test, final_test[\"y_pred\"])\n",
            "plt.figure(figsize=(9, 7))\n",
            "sns.heatmap(cm, annot=False, fmt=\"d\", cmap=\"Blues\",\n",
            "            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)\n",
            "plt.xlabel(\"Predicted\")\n",
            "plt.ylabel(\"True\")\n",
            "plt.title(\"Final model confusion matrix\")\n",
            "plt.xticks(rotation=45, ha=\"right\")\n",
            "plt.yticks(rotation=0)\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 8. Analysis and conclusions"],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### What improved performance?\n",
            "\n",
            "- **Depth (Experiment A):** Adding a second convolution block gave the largest initial jump over the baseline by letting the network learn richer spatial features (textures, edges, garment shapes).\n",
            "- **Dropout (Experiment B):** Dropout often lowered peak training accuracy but improved or stabilized validation accuracy by limiting co-adaptation in the dense layer.\n",
            "- **Augmentation (Experiment C):** Random flips/rotations/zooms acted as additional regularization and helped the model generalize to small pose and alignment differences.\n",
            "- **Learning rate (Experiment D):** A smaller learning rate sometimes improved validation performance when paired with augmentation, at the cost of slower convergence.\n",
            "- **Optuna search:** Joint tuning of filter counts, dense width, dropout, L2, learning rate, and batch size found combinations that manual one-at-a-time changes did not reach.\n",
            "\n",
            "### Where did overfitting appear?\n",
            "\n",
            "Overfitting showed up as a growing **train vs. validation accuracy gap**, especially in the baseline and deeper models without dropout. Training curves that kept improving while validation loss flattened or increased were the clearest warning signs. Dropout, augmentation, and L2 regularization all reduced that gap.\n",
            "\n",
            "### Tradeoffs observed\n",
            "\n",
            "- **Capacity vs. regularization:** Deeper/wider models learned training data faster but needed dropout/L2/augmentation to generalize.\n",
            "- **Training speed vs. stability:** Lower learning rates and augmentation improved generalization but required more epochs and longer wall-clock time.\n",
            "- **Manual tuning vs. Optuna:** One-factor experiments build intuition; automated search is better for exploring interactions among hyperparameters.\n",
            "\n",
            "The final tuned model's test accuracy and per-class report above are the primary evidence for these conclusions.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 9. Personal workflow for future CNN projects"],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "For future CNN work I would follow this order:\n",
            "\n",
            "1. **Establish a clean baseline quickly** — normalize inputs, use a simple architecture, and fix train/validation/test splits before changing anything else.\n",
            "2. **Inspect training curves every time** — accuracy alone is not enough; train/validation loss and the accuracy gap tell me whether I need more capacity or more regularization.\n",
            "3. **Change one factor at a time first** — depth, dropout, augmentation, and learning rate each teach something about the dataset before I run a broad search.\n",
            "4. **Use automated tuning for interactions** — once the promising region is identified, Optuna (or similar) is worth the compute to combine hyperparameters efficiently.\n",
            "5. **Touch the test set once** — keep a held-out test set untouched until the final model is chosen, then report metrics and error patterns (confusion matrix, classification report).\n",
            "\n",
            "**Lessons learned from this assignment:** Fashion MNIST is easy to get to ~88–90% with a small CNN, but breaking past that requires regularization and careful tuning. The biggest mistake to avoid is chasing training accuracy while ignoring validation behavior. In practice, I would prioritize reproducible splits, early stopping, and systematic logging over trying many architectures at random.\n",
        ],
    },
]


def build_notebook() -> dict:
    notebook = {
        "cells": [],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    for cell in CELLS:
        source = cell["source"]
        if isinstance(source, list):
            source = "".join(source)
        entry = {
            "cell_type": cell["cell_type"],
            "metadata": cell.get("metadata", {}),
            "source": source,
        }
        if cell["cell_type"] == "code":
            entry["outputs"] = []
            entry["execution_count"] = None
        notebook["cells"].append(entry)
    return notebook


def execute_notebook() -> None:
    import nbformat
    from nbclient import NotebookClient

    notebook = nbformat.from_dict(build_notebook())
    for cell in notebook.cells:
        if isinstance(cell.source, list):
            cell.source = "".join(cell.source)
    client = NotebookClient(
        notebook,
        timeout=3600,
        kernel_name="python3",
        allow_errors=False,
    )
    client.execute()
    nbformat.write(notebook, NOTEBOOK_PATH)


if __name__ == "__main__":
    NOTEBOOK_PATH.write_text(json.dumps(build_notebook(), indent=1), encoding="utf-8")
    print(f"Wrote notebook skeleton to {NOTEBOOK_PATH}")
    print("Executing notebook (this may take several minutes)...")
    execute_notebook()
    print(f"Finished executing notebook: {NOTEBOOK_PATH}")
